
version: 0.2
    
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:                                                                 
      - pip install --upgrade pip&&\
      - pip install -r .aws-sam/build/ProducerFunction/requirements.txt
      - pip install aws-sam-cli --upgrade
  build:
    commands:
      - sam deploy
  post_build:
    commands:
      - echo Build completed on `date`