version: 0.2
    
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install -r labeler/hello_world/requirements.txt
      - pip install --upgrade aws-sam-cli
  build:
    commands:
      - make deploy_labeler
  post_build:
    commands:
      - echo Build completed on `date`